server:
  port: 8100

spring:
  application:
    name: guli-eureka
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
    registerWithEureka: false
    fetchRegistry: false

sms:
  IP:111.111.111.111
