server:
  port: 8004
spring:
  application:
    name: guli-ucenter
  datasource:
    driver-class-name:
    url:
    username:
    password:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath:com/guli/ucenter/mapper/xml/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka/
  instance:
    prefer-ip-address: true
wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: 9864a18f5e456be9446635c07abcb4a0
    redirect_url: http://guli.shop/api/ucenter/wx/callback